// Test file with mock prompts + messages

export const testMessages = [
  {
    id: '1',
    role: 'user',
    content: "Show me Bitcoin's price chart for the last 30 days",
  },
  {
    id: '2',
    role: 'assistant',
    content:
      "Here's Bitcoin's price chart for the last 30 days:\n\n**BTC/USD Analysis:**\n- Current Price: $42,850\n- 30-day change: +12.5%\n- Volume: $28.4B\n\nThe chart shows strong bullish momentum with key resistance at $45,000. Recent institutional buying has driven the rally, with support levels holding at $40,000.",
  },
  {
    id: '3',
    role: 'user',
    content: 'What about Ethereum? How is ETH performing compared to BTC?',
  },
  {
    id: '4',
    role: 'assistant',
    content:
      '**Ethereum vs Bitcoin Comparison:**\n\n**ETH Performance:**\n- Current Price: $2,680\n- 30-day change: +8.2%\n- ETH/BTC ratio: 0.0625\n\n**Key Differences:**\n• Bitcoin leading the rally with stronger momentum\n• Ethereum showing steady growth but lagging BTC\n• DeFi activity on Ethereum remains strong\n• Upcoming Ethereum upgrades could boost performance\n\n**Recommendation:** Both showing bullish trends, but Bitcoin currently has stronger momentum.',
  },
  {
    id: '5',
    role: 'user',
    content: "Show me Bitcoin's price chart for the last 30 days",
  },
  {
    id: '6',
    role: 'assistant',
    content:
      "Here's Bitcoin's price chart for the last 30 days:\n\n**BTC/USD Analysis:**\n- Current Price: $42,850\n- 30-day change: +12.5%\n- Volume: $28.4B\n\nThe chart shows strong bullish momentum with key resistance at $45,000. Recent institutional buying has driven the rally, with support levels holding at $40,000.",
  },
  {
    id: '7',
    role: 'user',
    content: 'What about Ethereum? How is ETH performing compared to BTC?',
  },
  {
    id: '8',
    role: 'assistant',
    content:
      '**Ethereum vs Bitcoin Comparison:**\n\n**ETH Performance:**\n- Current Price: $2,680\n- 30-day change: +8.2%\n- ETH/BTC ratio: 0.0625\n\n**Key Differences:**\n• Bitcoin leading the rally with stronger momentum\n• Ethereum showing steady growth but lagging BTC\n• DeFi activity on Ethereum remains strong\n• Upcoming Ethereum upgrades could boost performance\n\n**Recommendation:** Both showing bullish trends, but Bitcoin currently has stronger momentum.',
  },
]

interface TestButtonsProps {
  onAddMessage: (message: {
    id: string
    role: 'user' | 'assistant'
    content: string
    shouldAnimate?: boolean
  }) => void
  onSetLoading: (loading: boolean) => void
}

export default function TestButtons({
  onAddMessage,
  onSetLoading,
}: TestButtonsProps) {
  const addUserMessage = (content: string) => {
    const userMessage = {
      id: `test-user-${Date.now()}`,
      role: 'user' as const,
      content,
    }
    onAddMessage(userMessage)
  }

  const addAssistantMessage = (content: string, delay = 2000) => {
    setTimeout(() => {
      onSetLoading(false)
      const assistantMessage = {
        id: `test-assistant-${Date.now()}`,
        role: 'assistant' as const,
        content,
        shouldAnimate: true,
      }
      onAddMessage(assistantMessage)
    }, delay)
    onSetLoading(true)
  }

  const testPermissions = () => {
    addUserMessage(
      'Set up permissions for treasury role to deposit USDC into Aave v3',
    )
    addAssistantMessage(`# DeFi Permission Granted

## Transaction Details
- **Protocol**: AAVE_V3
- **Action**: deposit
- **Chain**: Ethereum (eth)
- **Role**: treasury
- **Operation**: ALLOW

## Generated Transactions
### Transaction 1
- **To**: \`0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2\`
- **Value**: 0 ETH
- **Method**: \`approve\`
- **Parameters**: 
  - **spender**: \`0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2\`
  - **amount**: \`115792089237316195423570985008687907853269984665640564039457584007913129639935\`

### Transaction 2
- **To**: \`0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2\`
- **Value**: 0 ETH
- **Method**: \`supply\`
- **Parameters**: 
  - **asset**: \`0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48\`
  - **amount**: \`0\`
  - **onBehalfOf**: \`0x0000000000000000000000000000000000000000\`
  - **referralCode**: \`0\`

## Safe Transaction Builder Compatible
✅ This JSON response can be directly imported into Safe Transaction Builder for execution.

## Download Transaction File
\`\`\`json
{
  "version": "1.0",
  "chainId": "1",
  "createdAt": 1704067200000,
  "meta": {
    "name": "DeFi Kit Permissions Batch",
    "description": "Generated by DeFi Kit API for Zodiac Roles management",
    "txBuilderVersion": "1.16.2"
  },
  "transactions": [
    {
      "to": "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2",
      "value": "0",
      "data": null,
      "contractMethod": {
        "name": "approve",
        "payable": false,
        "inputs": [
          {"name": "spender", "type": "address"},
          {"name": "amount", "type": "uint256"}
        ]
      },
      "contractInputsValues": {
        "spender": "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2",
        "amount": "115792089237316195423570985008687907853269984665640564039457584007913129639935"
      }
    },
    {
      "to": "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2",
      "value": "0",
      "data": null,
      "contractMethod": {
        "name": "supply",
        "payable": false,
        "inputs": [
          {"name": "asset", "type": "address"},
          {"name": "amount", "type": "uint256"},
          {"name": "onBehalfOf", "type": "address"},
          {"name": "referralCode", "type": "uint16"}
        ]
      },
      "contractInputsValues": {
        "asset": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "amount": "0",
        "onBehalfOf": "0x0000000000000000000000000000000000000000",
        "referralCode": "0"
      }
    }
  ]
}
\`\`\`

*2 transaction(s) ready for execution*`)
  }

  const testConversation = () => {
    addUserMessage(
      'What are the current gas fees on Ethereum? Should I wait to make transactions?',
    )
    addAssistantMessage(
      '**Current Ethereum Gas Analysis:**\n\n**Current Gas Prices:**\n- Standard: 25 gwei (~$2.50 for simple transfer)\n- Fast: 35 gwei (~$3.50 for simple transfer)\n- Instant: 45 gwei (~$4.50 for simple transfer)\n\n**Network Status:**\n- Current block utilization: 78%\n- Average block time: 12.1 seconds\n- Pending transactions: 125,000\n\n**Recommendations:**\n• **Wait if possible** - Gas prices typically drop during weekends\n• **Best times**: Late night UTC (2-6 AM) or early morning\n• **Avoid**: Market volatility periods and major NFT drops\n• **Use gas trackers** for real-time monitoring\n\n**Cost Optimization Tips:**\n1. Batch multiple transactions together\n2. Use Layer 2 solutions (Arbitrum, Optimism) for lower fees\n3. Set custom gas limits to avoid overpaying',
      2000,
    )
  }

  const testTxBuilder = () => {
    addUserMessage(
      'Build a Safe transaction to deposit 1000 USDC into Aave v3 on Ethereum for my Safe 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    )
    addAssistantMessage(
      `I'll build a Safe transaction for depositing 1000 USDC into Aave v3 on Ethereum.

\`\`\`json
{
  "request": {
    "protocol": "aave_v3",
    "action": "deposit",
    "chain": "eth",
    "market": "Core",
    "asset": "USDC",
    "amount": "1000",
    "sender": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  },
  "payload": {
    "kind": "safeTx",
    "chainId": 1,
    "safeTx": {
      "to": "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2",
      "value": "0",
      "operation": 0,
      "contractMethod": {
        "name": "supply",
        "payable": false,
        "inputs": [
          { "name": "asset", "type": "address" },
          { "name": "amount", "type": "uint256" },
          { "name": "onBehalfOf", "type": "address" },
          { "name": "referralCode", "type": "uint16" }
        ]
      },
      "contractInputsValues": {
        "asset": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "amount": "1000000000",
        "onBehalfOf": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "referralCode": "0"
      }
    },
    "preview": "Aave v3 Core deposit 1000 USDC on eth"
  }
}
\`\`\`

**Transaction Summary:**
- **Protocol:** Aave v3 Core Pool
- **Action:** Supply/Deposit
- **Asset:** 1000 USDC ($1,000)
- **Target:** Your Safe (0xaaaa...aaaa)
- **Network:** Ethereum Mainnet

This transaction will call the \`supply()\` function on the Aave v3 Pool contract, depositing your USDC and minting aUSDC tokens to your Safe. The JSON above is compatible with Safe Transaction Builder.

<DownloadButton data='{"request":{"protocol":"aave_v3","action":"deposit","chain":"eth","market":"Core","asset":"USDC","amount":"1000","sender":"0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},"payload":{"kind":"safeTx","chainId":1,"safeTx":{"to":"0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2","value":"0","operation":0,"contractMethod":{"name":"supply","payable":false,"inputs":[{"name":"asset","type":"address"},{"name":"amount","type":"uint256"},{"name":"onBehalfOf","type":"address"},{"name":"referralCode","type":"uint16"}]},"contractInputsValues":{"asset":"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48","amount":"1000000000","onBehalfOf":"0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","referralCode":"0"}},"preview":"Aave v3 Core deposit 1000 USDC on eth"}}' filename='aave-v3-deposit-1000-usdc.json' />`,
      2000,
    )
  }

  const testChart = () => {
    addUserMessage("Show me Bitcoin's price chart for the last 7 days")
    addAssistantMessage(
      `Here is a quick BTC price chart for the last 7 days.\n\n<MessariChart data='{"citationId":1,"entities":[{"entityType":"asset","entityId":"bitcoin"}],"dataset":"timeseries","metric":"price","start":"2024-10-01","end":"2024-10-07","tier":"demo","granularity":"daily","metricTimeseries":{"point_schema":[{"id":"t","name":"time","slug":"time","description":"Unix timestamp","is_timestamp":true,"format":"unix"},{"id":"o","name":"open","slug":"open","description":"","is_timestamp":false,"format":"number"},{"id":"h","name":"high","slug":"high","description":"","is_timestamp":false,"format":"number"},{"id":"l","name":"low","slug":"low","description":"","is_timestamp":false,"format":"number"},{"id":"c","name":"close","slug":"close","description":"","is_timestamp":false,"format":"number"},{"id":"v","name":"volume","slug":"volume","description":"","is_timestamp":false,"format":"number"}],"series":[{"key":"BTC","entity":{"id":"btc","name":"Bitcoin","symbol":"BTC","slug":"bitcoin"},"points":[[1727740800,27000,27500,26500,27200,1200000],[1727827200,27200,27600,26800,27450,1100000],[1727913600,27450,27900,27100,27600,1050000],[1728000000,27600,28100,27300,27950,950000],[1728086400,27950,28300,27600,28100,980000],[1728172800,28100,28500,27800,28350,990000],[1728259200,28350,28700,28100,28600,1020000]]}]}}' index='0' />\n\nLet me know if you want ETH next!`,
    )
  }

  const testMarkdown = () => {
    addUserMessage(
      'Give me a market overview with BTC and ETH data in a table format',
    )
    addAssistantMessage(
      `# Market Snapshot\n\n**BTC/ETH Overview**\n\n- BTC showing steady momentum\n- ETH lagging slightly but holding key support\n\n| Asset | Price | 24h | 7d |\n| --- | ---: | ---: | ---: |\n| BTC | $28,600 | +0.8% | +3.1% |\n| ETH | $1,820 | +0.3% | +1.2% |\n\n> Funding remains neutral; derivatives positioning is balanced.\n\nInline code like \`eth_call\` and a short code block:\n\n\`\`\`json\n{"action":"rebalance","target":"60% BTC / 40% ETH"}\n\`\`\`\n\n---\n\n[Open Glassnode](https://glassnode.com) for more analytics.`,
    )
  }

  return (
    <div className="ml-4 flex flex-wrap gap-2">
      <button
        className="ease rounded-full border bg-blue-100 px-2 py-1 text-sm text-blue-700 transition-colors hover:bg-blue-200"
        onClick={testPermissions}
      >
        Test Permissions
      </button>
      <button
        className="ease rounded-full border bg-green-100 px-2 py-1 text-sm text-green-700 transition-colors hover:bg-green-200"
        onClick={testConversation}
      >
        Test Conversation
      </button>
      <button
        className="ease rounded-full border bg-purple-100 px-2 py-1 text-sm text-purple-700 transition-colors hover:bg-purple-200"
        onClick={testTxBuilder}
      >
        Test TX Builder
      </button>
      <button
        className="ease rounded-full border bg-yellow-100 px-2 py-1 text-sm text-yellow-700 transition-colors hover:bg-yellow-200"
        onClick={testChart}
      >
        Test Chart
      </button>
      <button
        className="ease rounded-full border bg-gray-100 px-2 py-1 text-sm text-gray-700 transition-colors hover:bg-gray-200"
        onClick={testMarkdown}
      >
        Test Markdown
      </button>
    </div>
  )
}
