name: Migrate DB

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --prefer-offline

      - run: pnpm db:migrate
        working-directory: deployables/app
        env:
          POSTGRES_PRISMA_URL: postgres://prisma.${{ secrets.SUPABASE_PROJECT_ID }}:${{ secrets.DB_PASSWORD }}@aws-0-us-east-1.pooler.supabase.com:5432/postgres
