name: Release Extension

on:
  push:
    branches:
      - chore/fix-chrome-publish
  release:
    types: released

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Extension
    env:
      COMPANION_APP_URL: https://app.pilot.gnosisguild.org
    defaults:
      run:
        working-directory: ./deployables/extension
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install deps and build
        run: |
          pnpm install --prefer-offline
          pnpm build
        env:
          NODE_ENV: production
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: v3.18.0 #${{ github.event.release.tag_name }}

      - name: Update manifest.json with release tag
        run: pnpm update-manifest -v v3.18.0 #${{ github.event.release.tag_name }}

      - name: Create extension zip file
        run: pnpm zip

      # - name: Add zip to Github release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: ./deployables/extension/zodiac-pilot.zip

      - name: Publish to Chrome Web Store
        uses: puzzlers-labs/chrome-webstore-publish@v1.0.3
        with:
          extension_id: jklckajipokenkbbodifahogmidkekcb
          zip_file_path: ./deployables/extension/zodiac-pilot.zip
          client_id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
          publish_target: public
          expedited_review: true # This does not guarantee an expedited Review process. But it makes an attempt.

      # - name: Upload & release to Chrome Webstore
      #   uses: mnao305/chrome-extension-upload@v5.0.0
      #   with:
      #     file-path: ./deployables/extension/zodiac-pilot.zip
      #     extension-id: jklckajipokenkbbodifahogmidkekcb
      #     client-id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
      #     client-secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
      #     refresh-token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
      #     publish: true

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: gnosis-guild
          SENTRY_PROJECT: pilot-extension
        with:
          environment: production
