name: Release Extension

on:
  release:
    types: released

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Extension
    env:
      COMPANION_APP_URL: https://app.pilot.gnosisguild.org
    defaults:
      run:
        working-directory: ./deployables/extension
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install deps and build
        run: |
          pnpm install --prefer-offline
          pnpm build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Update manifest.json with release tag
        run: pnpm update-manifest -v ${{ github.event.release.tag_name }}

      - name: Create extension zip file
        run: pnpm zip

      - name: Add zip to Github release
        uses: softprops/action-gh-release@v2
        with:
          files: ./deployables/extension/zodiac-pilot.zip

      - name: Upload & release to Chrome Webstore
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: ./deployables/extension/zodiac-pilot.zip
          extension-id: jklckajipokenkbbodifahogmidkekcb
          client-id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
          publish: false

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: gnosis-guild
          SENTRY_PROJECT: pilot-extension
        with:
          environment: production
