name: Deploy Vnet API

on:
  push:
    branches: main
    paths: ['deployables/vnet-api/**', '**/vnet-api-release.yaml']

defaults:
  run:
    working-directory: ./deployables/vnet-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --prefer-offline
      - name: Publish
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          workingDirectory: deployables/vnet-api
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            TENDERLY_ACCESS_KEY
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
          TENDERLY_USER: gnosisguild
          TENDERLY_PROJECT: zodiac-pilot
