name: Vnet API Preview

on:
  pull_request:
    paths: ['deployables/vnet-api/**', '**/vnet-api-release.yaml']

defaults:
  run:
    working-directory: ./deployables/vnet-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --prefer-offline

      - uses: cloudflare/wrangler-action@v3
        id: preview
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: ./deployables/vnet-api
          command: versions upload

      - uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Vnet API preview

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          edit-mode: replace
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body: |
            ## Vnet API preview
            ${{ steps.preview.outputs.deployment-url }}

      # - name: Publish
      #   uses: cloudflare/wrangler-action@v3.14.1
      #   with:
      #     workingDirectory: deployables/vnet-api
      #     apiToken: ${{ secrets.CF_API_TOKEN }}
      #     environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      #     secrets: |
      #       TENDERLY_ACCESS_KEY
      #   env:
      #     TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
      #     TENDERLY_USER: gnosisguild
      #     TENDERLY_PROJECT: zodiac-pilot
